name = "ccip-serverless"
main = "./worker/index.ts"
compatibility_date = "2023-08-14"

[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "ccip-dev"
database_id = "ccip-dev"

[env.test]
[[env.test.d1_databases]]
binding = "DB"
database_name = "ccip-test"
database_id = "ccip-test"

[[ d1_databases ]]
binding = "DB"
database_name = "__DATABASE_NAME__"
database_id = "__DATABASE_ID__"
